version: 2
jobs:
  build:
    docker:
      - image: circleci/python:3.7

    working_directory: ~/repo


    steps:
      # 1 - Obtain repo from Git
      - checkout
      # 2 - Virtual environment and install dependencies
      - run:
          name: install dependencies
          command: |
            python3 -m venv venv
            . venv/bin/activate
            pip3 install -r requirements.txt

      # 3 - Run linter and tests
      - run:
          name: run tests
          command: |
            . venv/bin/activate
            flake8 --exclude=venv* --statistics
<<<<<<< HEAD:.circleci/config.yaml
            pytest -v --cov=calculator
=======
            pytest -v --cov=calculator
            

    
>>>>>>> ed68008be34a4a9154c863b7a5da2975caa7aaa6:.circleci/config.yml
